In [19]:
from scipy.stats import qmc
from math import *
import numpy as np
a0 = 0.1
b0 = 1
a1 = 2
b1 = 1
sample_points_2_index = 28 #采样点，2^n个point

In [20]:
sampler = qmc.LatinHypercube(d=3)
#sampler = qmc.LatinHypercube(d=3,optimization="random-cd")
sample = sampler.random(n=2**sample_points_2_index)
sample,sample.shape

(array([[0.63606305, 0.37019953, 0.94339424],
        [0.28111134, 0.42251089, 0.21391844],
        [0.12657945, 0.2819187 , 0.33344868],
        ...,
        [0.19828788, 0.98786272, 0.16586564],
        [0.08825148, 0.26564365, 0.06196446],
        [0.48881703, 0.02444964, 0.33835041]]),
 (268435456, 3))

In [21]:
l_bounds = -3.14
u_bounds = 3.14
fianl_sample = qmc.scale(sample, l_bounds, u_bounds)
fianl_sample,fianl_sample.shape

(array([[ 0.85447596, -0.81514694,  2.78451582],
        [-1.37462077, -0.48663163, -1.79659223],
        [-2.34508107, -1.36955055, -1.04594226],
        ...,
        [-1.89475212,  3.0637779 , -2.09836379],
        [-2.58578068, -1.4717579 , -2.75086319],
        [-0.07022904, -2.98645626, -1.01515945]]),
 (268435456, 3))

In [22]:
f0 = np.sin(fianl_sample[:,0]) + a0*np.sin(fianl_sample[:,1])**2 + b0*fianl_sample[:,2]**4*np.sin(fianl_sample[:,0])
f1 = np.sin(fianl_sample[:,0]) + a1*np.sin(fianl_sample[:,1])**2 + b1*fianl_sample[:,2]**4*np.sin(fianl_sample[:,0])
f0,f0.shape,f1,f1.shape

(array([ 46.1492128 , -11.17744658,  -1.47455304, ..., -19.32646792,
        -30.64260216,  -0.14230795]),
 (268435456,),
 array([ 47.15570212, -10.76192106,   0.34953045, ..., -19.31498637,
        -28.76117767,  -0.09694575]),
 (268435456,))

In [23]:
aver_f0 = np.mean(f0)
var_f0 = np.var(f0,ddof=0) # 第二个参数等于0代表就是正常的方差，如果算的是样本方差，就是分母是n-1的那个，则第二个参数设置为1
aver_f0,var_f0,np.mean(abs(f0 - f0.mean())**2)

(0.04778255119839548, 545.2785512392118, 545.2785512392118)

In [24]:
aver_f1 = np.mean(f1)
var_f1 = np.var(f1,ddof=0) # 第二个参数等于0代表就是正常的方差，如果算的是样本方差，就是分母是n-1的那个，则第二个参数设置为1
aver_f1,var_f1,np.mean(abs(f1 - f1.mean())**2)

(0.9982644041765645, 545.7773534934939, 545.7773534934939)