In [267]:
from scipy.stats import qmc
from math import *
import numpy as np
a0 = 0.1
b0 = 1
a1 = 2
b1 = 1
sample_points_2_index = 25 #采样点，2^n个point

In [268]:
sampler = qmc.Sobol(d=3, scramble=False)
sampler

In [269]:
sample = sampler.random_base2(m=sample_points_2_index)
sample, type(sample), sample.shape

(array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [5.00000000e-01, 5.00000000e-01, 5.00000000e-01],
        [7.50000000e-01, 2.50000000e-01, 2.50000000e-01],
        ...,
        [7.50000030e-01, 7.51960784e-01, 7.50013858e-01],
        [5.00000030e-01, 1.96078420e-03, 1.38580799e-05],
        [2.98023224e-08, 5.01960784e-01, 5.00013858e-01]]),
 numpy.ndarray,
 (33554432, 3))

In [270]:
l_bounds = -3.14
u_bounds = 3.14

In [271]:
fianl_sample = qmc.scale(sample, l_bounds, u_bounds)
fianl_sample

array([[-3.14000000e+00, -3.14000000e+00, -3.14000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.57000000e+00, -1.57000000e+00, -1.57000000e+00],
       ...,
       [ 1.57000019e+00,  1.58231372e+00,  1.57008703e+00],
       [ 1.87158585e-07, -3.12768628e+00, -3.13991297e+00],
       [-3.13999981e+00,  1.23137248e-02,  8.70287418e-05]])

-------------------------------------------下面三块代码是测试代码，无需理会-------------------------------

In [272]:
sin(1.57),sin(0.523598)

(0.9999996829318346, 0.49999932831201965)

In [278]:
#textnp = np.array(([1,2,3],[4,5,6]))
#textnp = np.array(([1.57,1.57,1.57],[0.523598,0.523598,0.523598]))
textnp = fianl_sample
textnp,np.sin(np.array(([1.57,1.57,1.57],[0.523598,0.523598,0.523598])))

(array([[-3.14000000e+00, -3.14000000e+00, -3.14000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 1.57000000e+00, -1.57000000e+00, -1.57000000e+00],
        ...,
        [ 1.57000019e+00,  1.58231372e+00,  1.57008703e+00],
        [ 1.87158585e-07, -3.12768628e+00, -3.13991297e+00],
        [-3.13999981e+00,  1.23137248e-02,  8.70287418e-05]]),
 array([[0.99999968, 0.99999968, 0.99999968],
        [0.49999933, 0.49999933, 0.49999933]]))

In [274]:
#f0 = np.zeros([2, 3])
#f0
#f0 = sin(textnp[:,0]) + a0*sin(textnp[:,1])**2 + b0*textnp[:,2]**4*sin(textnp[:,0])
f0_text = np.sin(textnp[:,0]) + a0*np.sin(textnp[:,1])**2 + b0*textnp[:,2]**4*np.sin(textnp[:,0])
f0_text

array([-1.56416916e-01,  0.00000000e+00,  7.17572970e+00, ...,
        7.17706378e+00,  3.77166373e-05, -1.57767806e-03])

-------------------------------------------测试代码结束-------------------------------

In [275]:
f0 = np.sin(fianl_sample[:,0]) + a0*np.sin(fianl_sample[:,1])**2 + b0*fianl_sample[:,2]**4*np.sin(fianl_sample[:,0])
f1 = np.sin(fianl_sample[:,0]) + a1*np.sin(fianl_sample[:,1])**2 + b1*fianl_sample[:,2]**4*np.sin(fianl_sample[:,0])
f0,f0.shape,f1,f1.shape

(array([-1.56416916e-01,  0.00000000e+00,  7.17572970e+00, ...,
         7.17706378e+00,  3.77166373e-05, -1.57767806e-03]),
 (33554432,),
 array([-1.56412097e-01,  0.00000000e+00,  9.07572850e+00, ...,
         9.07681176e+00,  4.05128934e-04, -1.28959977e-03]),
 (33554432,))

In [276]:
aver_f0 = np.mean(f0)
var_f0 = np.var(f0,ddof=0) # 第二个参数等于0代表就是正常的方差，如果算的是样本方差，就是分母是n-1的那个，则第二个参数设置为1
aver_f0,var_f0,np.mean(abs(f0 - f0.mean())**2)

(0.05002535971277557, 545.2264962432521, 545.2264962432521)

In [277]:
aver_f1 = np.mean(f1)
var_f1 = np.var(f1,ddof=0) # 第二个参数等于0代表就是正常的方差，如果算的是样本方差，就是分母是n-1的那个，则第二个参数设置为1
aver_f1,var_f1,np.mean(abs(f1 - f1.mean())**2)

(1.0005072126910355, 545.7249930151016, 545.7249930151016)